#!/usr/bin/env python3
"""Derive an exact order-two G,U,V,J certificate for a Laurent period.

Input:
    F(x,y) in Q[x^+/-1,y^+/-1].

Definitions:
    rho = 1 - t*F,
    Phi(t) = CT_xy(1/rho),
    Dx = x*d/dx,  Dy = y*d/dy,
    G(a,bx,by) = rho*a - Dx(rho)*bx - Dy(rho)*by,
    J(bx,by) = Dx(bx) + Dy(by).

For w = F^2, solve
    G[U;V] = E*w,
    U - J*V/2 = alpha*rho + beta*F.

The reduced columns for Phi, Phi', Phi'' give an operator
    A = p2(t)*D_t^2 + p1(t)*D_t + p0(t)
and the exact divergence certificate
    Xi = p2*V.

All correctness checks use explicit coefficient comparison.  The program does
not call a generic algebraic simplifier.  Reference terms are generated by
lattice convolution and checked independently by direct power expansion for the
first few powers.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
import textwrap
import time
from collections import defaultdict
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Sequence, TextIO, Tuple

import sympy as sp
from sympy.polys.domains import QQ
from sympy.polys.matrices import DomainMatrix
from sympy.polys.matrices.exceptions import DMNonInvertibleMatrixError

x, y, t, theta, n = sp.symbols("x y t theta n")
Point = Tuple[int, int]


def theta_operator_lines(operator: sp.Expr) -> List[str]:
    """Order by powers of t and factor each coefficient in theta."""
    expression = sp.expand(sp.sympify(operator))
    polynomial = sp.Poly(expression, t)
    lines: List[str] = []
    for power in range(polynomial.degree() + 1):
        coefficient = sp.factor(polynomial.coeff_monomial(t**power))
        if coefficient == 0:
            continue
        negative = coefficient.could_extract_minus_sign()
        body = -coefficient if negative else coefficient
        if power == 0:
            term_text = str(body)
        else:
            t_text = "t" if power == 1 else f"t**{power}"
            numeric, remainder = body.as_coeff_Mul()
            factors: List[str] = []
            if numeric != 1:
                factors.append(str(numeric))
            factors.append(t_text)
            if remainder != 1:
                remainder_text = str(remainder)
                if isinstance(remainder, sp.Add):
                    remainder_text = f"({remainder_text})"
                factors.append(remainder_text)
            term_text = "*".join(factors)
        if not lines:
            lines.append(("- " if negative else "") + term_text)
        else:
            lines.append(("- " if negative else "+ ") + term_text)
    return lines or ["0"]


@dataclass
class Progress:
    """Report major stages with every physical line at most ``width`` columns."""

    total: int
    enabled: bool = True
    stream: TextIO = sys.stderr
    width: int = 80
    index: int = 0
    started: float = field(default_factory=time.perf_counter)

    def emit(
        self,
        message: str,
        *,
        indent: str = "",
        continuation: str = "      ",
    ) -> None:
        if not self.enabled:
            return
        lines = textwrap.wrap(
            str(message),
            width=self.width,
            initial_indent=indent,
            subsequent_indent=continuation,
            break_long_words=True,
            break_on_hyphens=False,
        ) or [indent]
        for line in lines:
            print(line, file=self.stream, flush=True)

    def emit_done(self, elapsed: float, details: dict) -> None:
        base = f"[{self.index}/{self.total}] done in {elapsed:.3f} s"
        ordinary = [(key, value) for key, value in details.items() if key != "A_theta"]
        current = base
        for key, value in ordinary:
            addition = f" | {key}={value}"
            if len(current) + len(addition) <= self.width:
                current += addition
            else:
                self.emit(current)
                current = f"      {key}={value}"
        self.emit(current)
        if "A_theta" in details:
            self.emit("A_theta =", indent="      ", continuation="      ")
            for line in theta_operator_lines(details["A_theta"]):
                self.emit(line, indent="          ", continuation="          ")

    @contextmanager
    def stage(self, label: str) -> Iterator[dict]:
        self.index += 1
        stage_start = time.perf_counter()
        details: dict = {}
        if self.enabled:
            self.emit(f"[{self.index}/{self.total}] {label} ...")
        try:
            yield details
        except Exception as exc:
            if self.enabled:
                elapsed = time.perf_counter() - stage_start
                self.emit(
                    f"[{self.index}/{self.total}] FAILED after {elapsed:.3f} s: {exc}"
                )
            raise
        else:
            if self.enabled:
                elapsed = time.perf_counter() - stage_start
                self.emit_done(elapsed, details)

    def finish(self) -> None:
        if self.enabled:
            elapsed = time.perf_counter() - self.started
            self.emit(f"[done] total wall time {elapsed:.3f} s")


def cancel_rational(expr: sp.Expr) -> sp.Expr:
    """Cancel a rational expression; this is the named Q(t) normal form used here."""
    return sp.cancel(sp.sympify(expr))


def rational_is_zero(expr: sp.Expr) -> bool:
    """Decide zero in Q(t) by cancelling and testing the numerator polynomial."""
    numerator, _ = sp.fraction(cancel_rational(expr))
    return sp.Poly(sp.expand(numerator), t, domain=QQ).is_zero


def assert_zero_matrix(name: str, matrix: sp.MatrixBase) -> None:
    """Require every matrix entry to vanish in Q(t), reporting exact failures."""
    failures = []
    for row in range(matrix.rows):
        for column in range(matrix.cols):
            value = cancel_rational(matrix[row, column])
            if not rational_is_zero(value):
                failures.append((row, column, value))
                if len(failures) == 8:
                    break
        if len(failures) == 8:
            break
    if failures:
        raise AssertionError(f"{name} failed; first nonzero entries: {failures}")


def laurent_terms(expr: sp.Expr, *, allow_t: bool = False) -> Dict[Point, sp.Expr]:
    """Return the finite Laurent coefficient map {(x exponent,y exponent):c}."""
    result: Dict[Point, sp.Expr] = {}
    allowed = {t} if allow_t else set()
    for term in sp.Add.make_args(sp.expand(expr)):
        powers = term.as_powers_dict()
        i = int(powers.get(x, 0))
        j = int(powers.get(y, 0))
        coefficient = cancel_rational(term / (x**i * y**j))
        forbidden = coefficient.free_symbols - allowed
        if forbidden:
            raise ValueError(f"coefficient contains forbidden symbols: {coefficient}")
        result[(i, j)] = cancel_rational(result.get((i, j), 0) + coefficient)
    return {point: coefficient for point, coefficient in result.items() if coefficient != 0}


def constant_terms(F: sp.Expr, count: int) -> List[sp.Expr]:
    """Compute CT_xy(F^k), 0 <= k < count, by finite lattice convolution."""
    steps = laurent_terms(F)
    layer: Dict[Point, sp.Expr] = {(0, 0): sp.Integer(1)}
    answer: List[sp.Expr] = []
    for _ in range(count):
        answer.append(cancel_rational(layer.get((0, 0), 0)))
        next_layer: Dict[Point, sp.Expr] = defaultdict(lambda: sp.Integer(0))
        for (i, j), value in layer.items():
            for (r, s), weight in steps.items():
                next_layer[(i + r, j + s)] += value * weight
        layer = {
            point: cancel_rational(value)
            for point, value in next_layer.items()
            if value != 0
        }
    return answer


def constant_terms_by_direct_expansion(F: sp.Expr, count: int) -> List[sp.Expr]:
    """Compute CT_xy(F^k) by direct expansion for a small independent check."""
    if count < 0:
        raise ValueError("count must be nonnegative")
    answer: List[sp.Expr] = []
    power = sp.Integer(1)
    for _ in range(count):
        answer.append(cancel_rational(laurent_terms(sp.expand(power)).get((0, 0), 0)))
        power = sp.expand(power * F)
    return answer


def convex_hull(points: Iterable[Point]) -> List[Point]:
    """Return the counterclockwise convex hull without collinear interior points."""
    pts = sorted(set(points))
    if len(pts) <= 1:
        return pts

    def cross(origin: Point, a: Point, b: Point) -> int:
        return (a[0] - origin[0]) * (b[1] - origin[1]) - (a[1] - origin[1]) * (b[0] - origin[0])

    lower: List[Point] = []
    for point in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], point) <= 0:
            lower.pop()
        lower.append(point)

    upper: List[Point] = []
    for point in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], point) <= 0:
            upper.pop()
        upper.append(point)
    return lower[:-1] + upper[:-1]


def lattice_points_in_hull(vertices: Sequence[Point]) -> List[Point]:
    """Enumerate all integer points in a point, segment, or convex polygon."""
    if not vertices:
        return []
    if len(vertices) == 1:
        return [vertices[0]]
    if len(vertices) == 2:
        left, right = vertices
        di, dj = right[0] - left[0], right[1] - left[1]
        steps = math.gcd(abs(di), abs(dj))
        if steps == 0:
            return [left]
        si, sj = di // steps, dj // steps
        return sorted((left[0] + k * si, left[1] + k * sj)
                      for k in range(steps + 1))
    min_i, max_i = min(i for i, _ in vertices), max(i for i, _ in vertices)
    min_j, max_j = min(j for _, j in vertices), max(j for _, j in vertices)

    def cross(a: Point, b: Point, point: Point) -> int:
        return (b[0] - a[0]) * (point[1] - a[1]) - (b[1] - a[1]) * (point[0] - a[0])

    return [
        (i, j)
        for i in range(min_i, max_i + 1)
        for j in range(min_j, max_j + 1)
        if all(
            cross(vertices[k], vertices[(k + 1) % len(vertices)], (i, j)) >= 0
            for k in range(len(vertices))
        )
    ]


def support_basis(F: sp.Expr, dilation: int) -> List[Point]:
    """Use the lattice points of dilation*conv({0} union support(F))."""
    support = set(laurent_terms(F)) | {(0, 0)}
    hull = convex_hull(support)
    dilated_hull = [(dilation * i, dilation * j) for i, j in hull]
    return lattice_points_in_hull(dilated_hull)


def expression_vector(expr: sp.Expr, basis: Sequence[Point]) -> sp.Matrix:
    """Convert a Laurent expression to its coefficient column in a fixed basis."""
    index = {point: position for position, point in enumerate(basis)}
    vector = sp.MutableSparseMatrix(len(basis), 1, {})
    for point, coefficient in laurent_terms(expr, allow_t=True).items():
        if point not in index:
            raise ValueError(f"support point {point} is outside the selected basis")
        vector[index[point], 0] = coefficient
    return sp.SparseMatrix(vector)


def vector_expression(vector: sp.MatrixBase, basis: Sequence[Point]) -> sp.Expr:
    """Convert a coefficient column back to a Laurent expression."""
    terms = [
        cancel_rational(vector[k, 0]) * x**i * y**j
        for k, (i, j) in enumerate(basis)
        if vector[k, 0] != 0
    ]
    return cancel_rational(sp.Add(*terms)) if terms else sp.Integer(0)


def build_matrices(F: sp.Expr, dilation: int):
    """Construct B,C and sparse matrices G,E,J,RHO in the declared bases."""
    basis = support_basis(F, dilation)
    F_terms = laurent_terms(F)
    ambient = sorted(
        set(basis)
        | {(i + r, j + s) for (i, j) in basis for (r, s) in F_terms}
    )
    row = {point: index for index, point in enumerate(ambient)}
    d, m = len(basis), len(ambient)
    G = sp.MutableSparseMatrix(m, 3 * d, {})
    E = sp.MutableSparseMatrix(m, d, {})
    RHO = sp.MutableSparseMatrix(m, d, {})

    for column, (i, j) in enumerate(basis):
        G[row[(i, j)], column] = 1
        E[row[(i, j)], column] = 1
        RHO[row[(i, j)], column] = 1
        for (r, s), coefficient in F_terms.items():
            target = row[(i + r, j + s)]
            G[target, column] += -t * coefficient
            RHO[target, column] += -t * coefficient
            G[target, d + column] += t * r * coefficient
            G[target, 2 * d + column] += t * s * coefficient

    J = sp.MutableSparseMatrix(d, 2 * d, {})
    for column, (i, j) in enumerate(basis):
        J[column, column] = i
        J[column, d + column] = j
    return basis, ambient, *(sp.SparseMatrix(M) for M in (G, E, J, RHO))


def evaluate_at(matrix: sp.MatrixBase, value: int) -> sp.Matrix:
    """Evaluate a matrix at one integer value of t."""
    return sp.Matrix(matrix.subs(t, sp.Integer(value)))


def pivot_layout(matrix: sp.MatrixBase, rhs: sp.MatrixBase, value: int):
    """Choose generic pivot columns and independent rows at one exact sample."""
    evaluated = evaluate_at(matrix, value)
    evaluated_rhs = evaluate_at(rhs, value)
    augmented = DomainMatrix.from_Matrix(evaluated.row_join(evaluated_rhs)).convert_to(QQ)
    _, pivots = augmented.rref()
    variable_count = matrix.cols
    if variable_count in pivots:
        raise ArithmeticError(f"inconsistent evaluated system at t={value}")
    pivot_columns = [pivot for pivot in pivots if pivot < variable_count]
    pivot_block = evaluated[:, pivot_columns]
    _, independent_rows = DomainMatrix.from_Matrix(pivot_block.T).convert_to(QQ).rref()
    rows = list(independent_rows)
    if len(rows) != len(pivot_columns):
        raise ArithmeticError(f"failed to select a square pivot block at t={value}")
    return pivot_columns, rows


def solve_sample(matrix: sp.MatrixBase, rhs: sp.MatrixBase,
                 pivot_columns: Sequence[int], rows: Sequence[int], value: int) -> List[sp.Expr]:
    """Solve the fixed square pivot block exactly over Q at t=value."""
    square = evaluate_at(matrix.extract(rows, pivot_columns), value)
    sampled_rhs = evaluate_at(rhs.extract(rows, [0]), value)
    square_domain = DomainMatrix.from_Matrix(square).convert_to(QQ)
    rhs_domain = DomainMatrix.from_Matrix(sampled_rhs).convert_to(QQ)
    numerator, denominator = square_domain.solve_den_rref(rhs_domain)
    values = [cancel_rational(entry / denominator) for entry in numerator.to_Matrix()]
    full_left = evaluate_at(matrix[:, pivot_columns], value) * sp.Matrix(values)
    if full_left != evaluate_at(rhs, value):
        raise ArithmeticError(f"sample solution failed the full system at t={value}")
    return values


def rational_candidate(data: Sequence[Tuple[sp.Expr, sp.Expr]],
                       numerator_degree: int, denominator_degree: int) -> sp.Expr | None:
    """Fit one rational function by an explicit homogeneous coefficient system."""
    rows = []
    for abscissa, ordinate in data:
        rows.append(
            [abscissa**degree for degree in range(numerator_degree + 1)]
            + [-ordinate * abscissa**degree for degree in range(denominator_degree + 1)]
        )
    nullspace = DomainMatrix.from_Matrix(sp.Matrix(rows)).convert_to(QQ).nullspace()
    if nullspace.shape[0] != 1:
        return None
    vector = list(nullspace.to_Matrix()[0, :])
    numerator = sum(vector[index] * t**index for index in range(numerator_degree + 1))
    offset = numerator_degree + 1
    denominator = sum(
        vector[offset + index] * t**index for index in range(denominator_degree + 1)
    )
    if denominator == 0:
        return None
    return cancel_rational(numerator / denominator)


def reconstruct_rational(training: Sequence[Tuple[sp.Expr, sp.Expr]],
                         validation: Sequence[Tuple[sp.Expr, sp.Expr]],
                         max_total_degree: int) -> sp.Expr:
    """Return the least-total-degree rational function passing held-out samples."""
    if all(ordinate == 0 for _, ordinate in list(training) + list(validation)):
        return sp.Integer(0)
    for total_degree in range(max_total_degree + 1):
        for numerator_degree in range(total_degree + 1):
            denominator_degree = total_degree - numerator_degree
            candidate = rational_candidate(training, numerator_degree, denominator_degree)
            if candidate is None:
                continue
            if all(
                rational_is_zero(candidate.subs(t, abscissa) - ordinate)
                for abscissa, ordinate in validation
            ):
                return candidate
    raise ArithmeticError(
        f"rational reconstruction exceeded total degree {max_total_degree}"
    )


def exact_free_zero_solution(matrix: sp.MatrixBase, rhs: sp.MatrixBase,
                             max_total_degree: int = 10) -> sp.Matrix:
    """Solve over Q(t) by exact evaluation, interpolation, and full replay."""
    training_count = max_total_degree + 1
    validation_count = 3
    candidate_values = range(1, 65)

    pivot_columns = None
    rows = None
    sample_table: Dict[int, List[sp.Expr]] = {}
    for value in candidate_values:
        if pivot_columns is None:
            try:
                pivot_columns, rows = pivot_layout(matrix, rhs, value)
            except ArithmeticError:
                continue
        try:
            sample_table[value] = solve_sample(matrix, rhs, pivot_columns, rows, value)
        except (ArithmeticError, DMNonInvertibleMatrixError, ZeroDivisionError):
            continue
        if len(sample_table) >= training_count + validation_count:
            break

    if pivot_columns is None or rows is None:
        raise ArithmeticError("no regular evaluation point found for the reduction system")
    if len(sample_table) < training_count + validation_count:
        raise ArithmeticError("not enough regular samples for rational reconstruction")

    sample_values = list(sample_table)
    training_values = sample_values[:training_count]
    validation_values = sample_values[training_count:training_count + validation_count]
    pivot_solution = []
    for index in range(len(pivot_columns)):
        training = [(sp.Integer(value), sample_table[value][index]) for value in training_values]
        validation = [(sp.Integer(value), sample_table[value][index]) for value in validation_values]
        pivot_solution.append(reconstruct_rational(training, validation, max_total_degree))

    solution = sp.MutableSparseMatrix(matrix.cols, 1, {})
    for column, value in zip(pivot_columns, pivot_solution):
        solution[column, 0] = value
    solution = sp.SparseMatrix(solution)
    assert_zero_matrix("interpolated exact system", matrix * solution - rhs)
    return solution


def primitive_annihilator(values: Sequence[sp.Expr]) -> Tuple[sp.Expr, sp.Expr, sp.Expr]:
    """Clear denominators, polynomial gcd, coefficient denominators, and content."""
    values = [cancel_rational(value) for value in values]
    common_denominator = sp.Integer(1)
    for value in values:
        common_denominator = sp.lcm(common_denominator, sp.denom(value))
    polynomials = [
        sp.Poly(sp.expand(cancel_rational(common_denominator * value)), t, domain=QQ)
        for value in values
    ]
    common_polynomial = polynomials[0]
    for polynomial in polynomials[1:]:
        common_polynomial = sp.gcd(common_polynomial, polynomial)
    polynomials = [sp.quo(polynomial, common_polynomial) for polynomial in polynomials]

    coefficient_lcm = 1
    for polynomial in polynomials:
        for coefficient in polynomial.all_coeffs():
            coefficient_lcm = sp.ilcm(coefficient_lcm, int(sp.denom(coefficient)))
    expressions = [sp.expand(coefficient_lcm * polynomial.as_expr()) for polynomial in polynomials]

    content = 0
    for expression in expressions:
        for coefficient in sp.Poly(expression, t, domain=QQ).all_coeffs():
            content = math.gcd(content, abs(int(coefficient)))
    if content > 1:
        expressions = [sp.expand(expression / content) for expression in expressions]

    p2_poly = sp.Poly(expressions[2], t, domain=QQ)
    quotient, remainder = sp.div(p2_poly, sp.Poly(t, t, domain=QQ))
    sign_probe = quotient.eval(0) if remainder.is_zero else sp.Integer(0)
    if sign_probe == 0:
        sign_probe = p2_poly.LC()
    if sign_probe < 0:
        expressions = [-expression for expression in expressions]
    return tuple(expressions)  # type: ignore[return-value]


def standard_to_theta(p0: sp.Expr, p1: sp.Expr, p2: sp.Expr) -> sp.Expr:
    """Return a primitive polynomial theta-form equivalent to t*A."""
    raw = p2 * (theta**2 - theta) / t + p1 * theta + t * p0
    numerator, _ = sp.fraction(cancel_rational(raw))
    polynomial = sp.Poly(sp.expand(numerator), t, theta, domain=QQ)
    denominator_lcm = 1
    for coefficient in polynomial.coeffs():
        denominator_lcm = sp.ilcm(denominator_lcm, int(sp.denom(coefficient)))
    expression = sp.expand(denominator_lcm * polynomial.as_expr())
    coefficients = [abs(int(c)) for c in sp.Poly(expression, t, theta).coeffs() if c != 0]
    content = 0
    for coefficient in coefficients:
        content = math.gcd(content, coefficient)
    if content > 1:
        expression = sp.expand(expression / content)
    return expression


def theta_recurrence(A_theta: sp.Expr) -> Dict[int, sp.Expr]:
    """For A_theta=sum t^k Q_k(theta), return the coefficients Q_k(n-k)."""
    recurrence: Dict[int, sp.Expr] = {}
    for (shift,), coefficient in sp.Poly(sp.expand(A_theta), t).terms():
        recurrence[shift] = sp.expand(coefficient.subs(theta, n - shift))
    return dict(sorted(recurrence.items()))


def recurrence_holds(recurrence: Dict[int, sp.Expr], terms: Sequence[sp.Expr]) -> bool:
    """Check the recurrence against every available independently computed term."""
    for index in range(len(terms)):
        residual = sp.Integer(0)
        for shift, coefficient in recurrence.items():
            if index - shift >= 0:
                residual += coefficient.subs(n, index) * terms[index - shift]
        if not rational_is_zero(residual):
            return False
    return True


def build_order_two_system(G, E, J, F_vector, F2_vector, rho_vector):
    """Build the block system for U,Vx,Vy,alpha,beta."""
    m, d = G.rows, F_vector.rows
    top = G.row_join(sp.zeros(m, 2))
    bottom = sp.eye(d).row_join(-J / 2).row_join(-rho_vector).row_join(-F_vector)
    system = sp.SparseMatrix.vstack(sp.SparseMatrix(top), sp.SparseMatrix(bottom))
    rhs = sp.SparseMatrix.vstack(E * F2_vector, sp.zeros(d, 1))
    return system, rhs


def unpack_reduction(solution: sp.MatrixBase, d: int):
    """Split a block-system solution into U,Vx,Vy,alpha,beta."""
    U = solution[:d, :]
    Vx = solution[d : 2 * d, :]
    Vy = solution[2 * d : 3 * d, :]
    V = sp.SparseMatrix.vstack(sp.SparseMatrix(Vx), sp.SparseMatrix(Vy))
    alpha = cancel_rational(solution[3 * d, 0])
    beta = cancel_rational(solution[3 * d + 1, 0])
    return U, Vx, Vy, V, alpha, beta


def verify_reduction(G, E, J, F2_vector, rho_vector, F_vector, U, V, alpha, beta):
    """Verify the G,U,V,J equation and the order-two closure equation."""
    assert_zero_matrix("G[U;V]-E*F^2", G * sp.Matrix.vstack(U, V) - E * F2_vector)
    lower2 = U - J * V / 2
    assert_zero_matrix(
        "Lower_2-alpha*rho-beta*F",
        lower2 - alpha * rho_vector - beta * F_vector,
    )
    return lower2


def derive_operator(alpha: sp.Expr, beta: sp.Expr):
    """Derive the primitive kernel of the reduced-column matrix explicitly."""
    X = sp.Matrix([[1, 0, 2 * alpha], [0, 1, 2 * beta]])
    p0, p1, p2 = primitive_annihilator((-2 * alpha, -2 * beta, sp.Integer(1)))
    assert_zero_matrix("X*(p0,p1,p2)^T", X * sp.Matrix([p0, p1, p2]))
    A_theta = standard_to_theta(p0, p1, p2)
    return X, p0, p1, p2, A_theta


def verify_Xi(F, rho, basis, G, E, J, RHO, p0, p1, p2, V):
    """Construct Xi=p2*V and verify the cleared numerator identity."""
    Xi = p2 * V
    Bblock = G[:, len(basis) : 3 * len(basis)]
    left_source = sp.expand(p0 * rho**2 + p1 * F * rho + 2 * p2 * F**2)
    left = E * expression_vector(left_source, basis)
    right = RHO * J * Xi + 2 * Bblock * Xi
    assert_zero_matrix("exact Xi certificate", left - right)
    return Xi


def display_expr(expr: sp.Expr) -> str:
    """Return the explicit cancelled Q(t,x,y) form used in publication data."""
    return str(cancel_rational(expr))


def sparse_matrix_record(matrix, row_labels: Sequence[str], column_labels: Sequence[str]) -> dict:
    """Serialize a sparse matrix using coordinate triples."""
    entries = []
    for i in range(matrix.rows):
        for j in range(matrix.cols):
            if matrix[i, j] != 0:
                entries.append([i, j, display_expr(matrix[i, j])])
    return {
        "shape": [matrix.rows, matrix.cols],
        "rows": list(row_labels),
        "columns": list(column_labels),
        "nonzero_count": len(entries),
        "entries": entries,
    }


def sparse_vector_record(vector, labels: Sequence[str]) -> dict:
    """Serialize a sparse vector using indexed entries."""
    entries = [
        [i, display_expr(vector[i, 0])]
        for i in range(vector.rows)
        if vector[i, 0] != 0
    ]
    return {
        "shape": [vector.rows, 1],
        "labels": list(labels),
        "nonzero_count": len(entries),
        "entries": entries,
    }


def make_serialization_labels(basis: Sequence[Point], ambient: Sequence[Point]):
    """Create deterministic row, column, and vector labels."""
    basis_labels = [f"x^{i}*y^{j}" for i, j in basis]
    ambient_labels = [f"x^{i}*y^{j}" for i, j in ambient]
    G_columns = (
        [f"a[{i},{j}]" for i, j in basis]
        + [f"bx[{i},{j}]" for i, j in basis]
        + [f"by[{i},{j}]" for i, j in basis]
    )
    J_columns = [f"bx[{i},{j}]" for i, j in basis] + [f"by[{i},{j}]" for i, j in basis]
    return basis_labels, ambient_labels, G_columns, J_columns


def make_reduction_record(*, U, Vx, Vy, lower2, alpha, beta, basis, basis_labels):
    """Serialize U,V,alpha,beta and the lowered numerator."""
    return {
        "identity": "G[U;V]=E*F^2",
        "lowering": "Lower_2=U-(1/2)*J*V=alpha*rho+beta*F",
        "U": sparse_vector_record(U, basis_labels),
        "Vx": sparse_vector_record(Vx, basis_labels),
        "Vy": sparse_vector_record(Vy, basis_labels),
        "alpha": display_expr(alpha),
        "beta": display_expr(beta),
        "U_expression": display_expr(vector_expression(U, basis)),
        "Vx_expression": display_expr(vector_expression(Vx, basis)),
        "Vy_expression": display_expr(vector_expression(Vy, basis)),
        "Lower2_expression": display_expr(vector_expression(lower2, basis)),
    }


def make_operator_records(*, X, p0, p1, p2, A_theta, Xi, basis, basis_labels):
    """Serialize the reduced columns, operator A, and witness Xi."""
    d = len(basis)
    Xi_x, Xi_y = Xi[:d, :], Xi[d:, :]
    reduced_columns = [
        ["1", "0", display_expr(X[0, 2])],
        ["0", "1", display_expr(X[1, 2])],
    ]
    operator = {
        "standard_form": {
            "p0": display_expr(p0),
            "p1": display_expr(p1),
            "p2": display_expr(p2),
            "meaning": "p2*Phi''+p1*Phi'+p0*Phi=0",
        },
        "theta_form": display_expr(A_theta),
    }
    witness = {
        "identity": "A(1/rho)=Dx(Xi_x/rho^2)+Dy(Xi_y/rho^2)",
        "construction": "Xi=p2*V",
        "Xi_x": sparse_vector_record(Xi_x, basis_labels),
        "Xi_y": sparse_vector_record(Xi_y, basis_labels),
        "Xi_x_expression": display_expr(vector_expression(Xi_x, basis)),
        "Xi_y_expression": display_expr(vector_expression(Xi_y, basis)),
    }
    return reduced_columns, operator, witness


def build_certificate_record(*, model, F, rho, dilation, term_count, direct_check_count,
                             basis, ambient, G, J, U, Vx, Vy, lower2, alpha, beta, X,
                             p0, p1, p2, A_theta, Xi, recurrence, terms):
    """Assemble the deterministic publication certificate object."""
    basis_labels, ambient_labels, G_columns, J_columns = make_serialization_labels(
        basis, ambient
    )
    reduction = make_reduction_record(
        U=U, Vx=Vx, Vy=Vy, lower2=lower2, alpha=alpha, beta=beta,
        basis=basis, basis_labels=basis_labels,
    )
    reduced_columns, operator, witness = make_operator_records(
        X=X, p0=p0, p1=p1, p2=p2, A_theta=A_theta, Xi=Xi,
        basis=basis, basis_labels=basis_labels,
    )
    return {
        "schema": "laurent-period-guvj-certificate-v1",
        "model": model,
        "input": {
            "F": str(sp.expand(F)),
            "rho": str(sp.expand(rho)),
            "coefficient_field": "Q(t)",
            "dilation": dilation,
            "term_count": term_count,
            "direct_check_count": direct_check_count,
        },
        "basis": {
            "B": [[i, j] for i, j in basis],
            "C": [[i, j] for i, j in ambient],
        },
        "matrices": {
            "G": sparse_matrix_record(G, ambient_labels, G_columns),
            "J": sparse_matrix_record(J, basis_labels, J_columns),
        },
        "reduction": reduction,
        "reduced_columns_X": reduced_columns,
        "annihilator_A": operator,
        "certificate_Xi": witness,
        "recurrence": {
            "convention": "sum_k Q_k(n-k)*a(n-k)=0 when A_theta=sum_k t^k Q_k(theta)",
            "shift_polynomials": {str(k): display_expr(value) for k, value in recurrence.items()},
        },
        "constant_terms": [str(value) for value in terms],
        "checks": {
            "GUVJ_reduction_exact": True,
            "X_kernel_exact": True,
            "Xi_certificate_exact": True,
            "recurrence_exact_on_computed_terms": True,
            "direct_power_terms_exact": True,
        },
    }

def validated_direct_check_count(term_count: int, direct_check_count: int) -> int:
    """Validate term-count options and return the effective direct-check count."""
    if term_count < 1:
        raise ValueError("term_count must be positive")
    if direct_check_count < 0:
        raise ValueError("direct_check_count must be nonnegative")
    return min(direct_check_count, term_count)


def checked_term_data(F: sp.Expr, A_theta: sp.Expr, term_count: int,
                      direct_check_count: int):
    """Generate reference terms twice and verify the recurrence."""
    recurrence = theta_recurrence(A_theta)
    terms = constant_terms(F, term_count)
    if not recurrence_holds(recurrence, terms):
        raise AssertionError("recurrence failed on lattice-convolution terms")
    direct_terms = constant_terms_by_direct_expansion(F, direct_check_count)
    if direct_terms != terms[:direct_check_count]:
        raise AssertionError(
            f"direct-power term mismatch: {direct_terms} != {terms[:direct_check_count]}"
        )
    return recurrence, terms


def derive_certificate(F: sp.Expr, *, model: str = "custom", dilation: int = 2,
                       term_count: int = 12, direct_check_count: int = 5,
                       report_progress: bool = True) -> dict:
    """Run the complete exact derivation and return one certificate record."""
    direct_check_count = validated_direct_check_count(term_count, direct_check_count)
    progress = Progress(total=8, enabled=report_progress)

    with progress.stage("normalize Laurent input") as info:
        F = sp.expand(F)
        rho = sp.expand(1 - t * F)
        info["support(F)"] = len(laurent_terms(F))

    with progress.stage("build support bases and G,E,J matrices") as info:
        basis, ambient, G, E, J, RHO = build_matrices(F, dilation)
        info["|B|"] = len(basis)
        info["|C|"] = len(ambient)
        info["G"] = f"{G.rows}x{G.cols}"

    with progress.stage("build the order-two block system") as info:
        F_vector = expression_vector(F, basis)
        F2_vector = expression_vector(F**2, basis)
        rho_vector = expression_vector(rho, basis)
        system, rhs = build_order_two_system(G, E, J, F_vector, F2_vector, rho_vector)
        info["system"] = f"{system.rows}x{system.cols}"

    with progress.stage("solve exactly over Q(t) by evaluation and interpolation") as info:
        solution = exact_free_zero_solution(system, rhs)
        info["max rational degree"] = 10
        U, Vx, Vy, V, alpha, beta = unpack_reduction(solution, len(basis))

    with progress.stage("verify G,U,V,J reduction"):
        lower2 = verify_reduction(G, E, J, F2_vector, rho_vector, F_vector,
                                  U, V, alpha, beta)

    with progress.stage("derive A and verify the Xi certificate") as info:
        X, p0, p1, p2, A_theta = derive_operator(alpha, beta)
        Xi = verify_Xi(F, rho, basis, G, E, J, RHO, p0, p1, p2, V)
        info["A_theta"] = A_theta

    with progress.stage("generate and cross-check reference terms") as info:
        recurrence, terms = checked_term_data(
            F, A_theta, term_count, direct_check_count
        )
        info["terms"] = len(terms)
        info["direct powers"] = direct_check_count

    with progress.stage("assemble publication certificate"):
        certificate = build_certificate_record(
            model=model, F=F, rho=rho, dilation=dilation, term_count=term_count,
            direct_check_count=direct_check_count,
            basis=basis, ambient=ambient, G=G, J=J, U=U, Vx=Vx, Vy=Vy,
            lower2=lower2, alpha=alpha, beta=beta, X=X,
            p0=p0, p1=p1, p2=p2, A_theta=A_theta, Xi=Xi,
            recurrence=recurrence, terms=terms,
        )

    progress.finish()
    return certificate


def parse_laurent(text: str) -> sp.Expr:
    """Parse a Laurent polynomial and reject symbols other than x and y."""
    expression = sp.sympify(text, locals={"x": x, "y": y})
    forbidden = expression.free_symbols - {x, y}
    if forbidden:
        raise ValueError(f"input contains forbidden symbols: {sorted(map(str, forbidden))}")
    laurent_terms(expression)
    return expression


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--F", required=True, help="Laurent polynomial in x,y")
    parser.add_argument("--model", default="custom")
    parser.add_argument("--dilation", type=int, default=2)
    parser.add_argument("--terms", type=int, default=12)
    parser.add_argument(
        "--direct-check-count", type=int, default=5,
        help="number of initial powers checked by direct expansion",
    )
    parser.add_argument("--output", type=Path, default=Path("certificate.json"))
    parser.add_argument("--quiet", action="store_true", help="suppress stage progress on stderr")
    args = parser.parse_args()

    certificate = derive_certificate(
        parse_laurent(args.F),
        model=args.model,
        dilation=args.dilation,
        term_count=args.terms,
        direct_check_count=args.direct_check_count,
        report_progress=not args.quiet,
    )
    args.output.write_text(json.dumps(certificate, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "model": certificate["model"],
        "G_shape": certificate["matrices"]["G"]["shape"],
        "G_nonzero_count": certificate["matrices"]["G"]["nonzero_count"],
        "J_shape": certificate["matrices"]["J"]["shape"],
        "theta_form": certificate["annihilator_A"]["theta_form"],
        "checks": certificate["checks"],
        "output": str(args.output),
    }, indent=2))


if __name__ == "__main__":
    main()
