#!/usr/bin/env python3
"""Write portable build provenance and SHA-256 digests for the MWE archive."""
from __future__ import annotations

import argparse
import hashlib
import platform
import sys
from pathlib import Path

EXCLUDE_PARTS = {"dist", "__pycache__"}


def digest(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--root", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()
    root = args.root.resolve()
    files = []
    for rel_dir in ("code", "data", "build/plots"):
        directory = root / rel_dir
        if directory.exists():
            files.extend(path for path in directory.rglob("*") if path.is_file())
    files = sorted(set(files), key=lambda p: str(p.relative_to(root)))
    lines = [
        "CIRCLE-LATTICE MWE BUILD INFO",
        "=" * 36,
        "This file is generated by code/build_info.py.",
        f"Python: {sys.version.splitlines()[0]}",
        f"Platform: {platform.platform()}",
        "",
        "SHA-256 (source, inputs, and generated SVG/PNG outputs)",
        "-" * 58,
    ]
    for path in files:
        lines.append(f"{digest(path)}  {path.relative_to(root)}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(args.out)


if __name__ == "__main__":
    main()
