#!/usr/bin/env python3
"""Transfer verified legacy case knowledge into canonical component JSON."""

from __future__ import annotations

import json
from pathlib import Path

CASES = ("A120588", "A120590", "A120593", "A120596")


def dump(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    for case_id in CASES:
        case_root = root / "examples" / case_id
        blob = json.loads((case_root / "case.json").read_text())
        objects = blob["objects"]
        mapping = {
            "terms": {"status": "verified", "terms": blob["terms"]},
            "inverse_map": {"status": "verified", **objects["shifted_generating_function"]},
            "coefficient_formula": {"status": "verified", **objects["closed_form"]},
            "matrices": {
                "status": "verified",
                "bases": objects["bases"],
                "matrices": objects["matrices"],
            },
            "recurrence": {
                "status": "verified",
                "recurrence": objects["p_recurrence"],
                "legacy_top_level": blob["recurrence"],
            },
            "certificate": {"status": "verified", **objects["rational_certificate"]},
            "ode": {
                "status": "verified",
                "from_recurrence": objects["ode_from_recurrence"],
                "direct": objects["direct_derivative_reduction"],
            },
        }
        for name, value in mapping.items():
            dump(case_root / "data" / f"{name}.json", value)

        manifest = json.loads((case_root / "manifest.json").read_text())
        manifest["family"] = "hanna_core_A120588_A120607"
        manifest["canonical"] = {
            "case_spec": "input/case_spec.json",
            **{name: f"data/{name}.json" for name in mapping},
            "tree_model": "data/tree_model.json",
            "checks": "checks/results.json",
            "human_text": "text/certificate.md",
            "release_payload": "release/payload.json",
        }
        for name in mapping:
            manifest["components"][name] = {
                "status": "verified",
                "canonical_path": f"data/{name}.json",
                "migrated_from": "case.json",
            }
        dump(case_root / "manifest.json", manifest)
        lines = [
            f"# {case_id} checklist",
            "",
            f"- Case state: `{manifest['case_state']}`",
            f"- Historical alias: `{manifest['aliases'][0]}`",
            "",
            "## Canonical analytic components",
            "",
        ]
        for name in mapping:
            lines.append(f"- [x] `{name}` verified — `data/{name}.json`")
        lines += [
            "- [ ] `tree_model` — `not_attempted` (`data/tree_model.json`)",
            "",
            "Generated by `src/normalize_existing_cases.py` from manifest status.",
            "",
        ]
        (case_root / "CHECKLIST.md").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
