#!/usr/bin/env python3
"""
harmonica_triangle.py

Reference implementation for the Harm.On.ica triangle.

Definitions
-----------
For N >= 0 and 0 <= M <= N, let T(N, M) count the number of dihedral
equivalence classes of survivor words obtained as follows.

Repeat-letter mode:
    Start from all words of length N over the alphabet {1, ..., N}.
    Recursively delete M positions.
    Canonicalize survivor words under rotation and reflection.

No-repeat mode:
    Start from the single word (1, 2, ..., N).
    Recursively delete M positions.
    Canonicalize survivor words under rotation and reflection.

The repeat-letter triangle is equivalently

    T(N, M) = bracelets(N, N - M),

where bracelets(q, L) is the number of length-L bracelets over q colors.

The no-repeat triangle is Pascal's triangle:

    T(N, M) = binomial(N, M).

This script contains both a brute-force implementation and a closed-form
implementation.  The brute-force implementation is intentionally retained as
an independent checker for small N.
"""

from __future__ import annotations

import argparse
from itertools import product
from math import comb, gcd
from typing import Callable, Iterable, Sequence


Word = tuple[int, ...]
Row = list[int]
Triangle = list[Row]


# ---------------------------------------------------------------------------
# Dihedral word operations
# ---------------------------------------------------------------------------

def rotate(word: Word, amount: int) -> Word:
    """Return word rotated left by amount positions."""
    if not word:
        return word
    amount %= len(word)
    return word[amount:] + word[:amount]


def reflect(word: Word) -> Word:
    """Return the reflected/reversed word."""
    return tuple(reversed(word))


def canonicalize(word: Word) -> Word:
    """
    Return the lexicographically least representative of word
    under the dihedral group generated by rotation and reflection.
    """
    if not word:
        return ()

    reflected = reflect(word)
    candidates = [
        candidate
        for k in range(len(word))
        for candidate in (rotate(word, k), rotate(reflected, k))
    ]
    return min(candidates)


def forget(word: Word) -> set[Word]:
    """
    Return all canonical one-position deletions of word.
    """
    return {
        canonicalize(word[:i] + word[i + 1:])
        for i in range(len(word))
    }


# ---------------------------------------------------------------------------
# Brute-force implementation
# ---------------------------------------------------------------------------

def all_words(alphabet_size: int, length: int) -> Iterable[Word]:
    """
    Generate all words of given length over alphabet {1, ..., alphabet_size}.
    """
    return product(range(1, alphabet_size + 1), repeat=length)


def deletion_layers(initial_words: Iterable[Word], max_deletions: int) -> Triangle:
    """
    Compute deletion layers by brute force.

    Row entry m is the number of distinct canonical survivor words after
    exactly m one-position deletions.
    """
    current = {canonicalize(tuple(word)) for word in initial_words}
    row = [len(current)]

    for _ in range(max_deletions):
        next_current: set[Word] = set()
        for word in current:
            next_current.update(forget(word))
        current = next_current
        row.append(len(current))

    return [row]


def brute_repeat_row(n: int) -> Row:
    """
    Brute-force row N in repeat-letter mode.

    This enumerates all N^N starting words, so it is only intended for
    small verification cases.
    """
    return deletion_layers(all_words(n, n), n)[0]


def brute_no_repeat_row(n: int) -> Row:
    """
    Brute-force row N in no-repeat mode.
    """
    return deletion_layers([tuple(range(1, n + 1))], n)[0]


# ---------------------------------------------------------------------------
# Closed-form implementation
# ---------------------------------------------------------------------------

def bracelets(colors: int, length: int) -> int:
    """
    Count bracelets of given length over a given number of colors.

    This is Burnside's lemma for the dihedral action on length positions.

    Rotation contribution:
        rotation by k fixes colors^gcd(length, k) words.

    Reflection contribution:
        odd length:
            each reflection fixes one position and pairs the rest.
        even length:
            half the reflections pass through opposite beads;
            half pass through opposite gaps.
    """
    q = colors
    n = length

    if n == 0:
        return 1

    rotation_total = sum(q ** gcd(n, k) for k in range(n))

    if n % 2 == 1:
        reflection_total = n * q ** ((n + 1) // 2)
    else:
        through_beads = (n // 2) * q ** (n // 2 + 1)
        through_gaps = (n // 2) * q ** (n // 2)
        reflection_total = through_beads + through_gaps

    return (rotation_total + reflection_total) // (2 * n)


def closed_repeat_row(n: int) -> Row:
    """
    Closed-form row N in repeat-letter mode.

    After M deletions, every word of survivor length N-M over alphabet
    {1, ..., N} is reachable.
    """
    return [bracelets(n, n - m) for m in range(n + 1)]


def closed_no_repeat_row(n: int) -> Row:
    """
    Closed-form row N in no-repeat mode.
    """
    return [comb(n, m) for m in range(n + 1)]


# ---------------------------------------------------------------------------
# Reporting and checks
# ---------------------------------------------------------------------------

def triangle(max_n: int, row_function: Callable[[int], Row]) -> Triangle:
    """Return rows 0 through max_n."""
    return [row_function(n) for n in range(max_n + 1)]


def row_sums(rows: Triangle) -> Row:
    """Return row sums."""
    return [sum(row) for row in rows]


def first_differences(values: Sequence[int]) -> Row:
    """Return first differences, with the first term retained."""
    if not values:
        return []
    return [values[0]] + [
        values[i] - values[i - 1]
        for i in range(1, len(values))
    ]


def tail_differences(rows: Triangle) -> Triangle:
    """
    Compare row N with row N+1 after removing row N+1's leading entry.

    D(N, M) = T(N+1, M+1) - T(N, M).
    """
    return [
        [
            rows[n + 1][m + 1] - rows[n][m]
            for m in range(len(rows[n]))
        ]
        for n in range(len(rows) - 1)
    ]


def csv(values: Iterable[int]) -> str:
    """Comma-separated searchable integer line."""
    return ",".join(str(value) for value in values)


def semicolon_rows(rows: Triangle) -> str:
    """Semicolon-separated searchable triangle."""
    return ";\n  ".join(csv(row) for row in rows)


def print_report(rows: Triangle) -> None:
    """Print triangle, row sums, first differences, and tail differences."""
    sums = row_sums(rows)

    print("triangle:")
    print(semicolon_rows(rows))
    print()
    print("sequence:")
    print(csv(sums))
    print()
    print("first_differences:")
    print(csv(first_differences(sums)))
    print()
    print("tail_differences:")
    print(semicolon_rows(tail_differences(rows)))


def assert_known_values() -> None:
    """
    Check small known rows.

    These are deliberately small enough to be inspectable by hand.
    """
    known_repeat = [
        [1],
        [1, 1],
        [3, 2, 1],
        [10, 6, 3, 1],
        [55, 20, 10, 4, 1],
        [377, 120, 35, 15, 5, 1],
    ]

    known_no_repeat = [
        [1],
        [1, 1],
        [1, 2, 1],
        [1, 3, 3, 1],
        [1, 4, 6, 4, 1],
        [1, 5, 10, 10, 5, 1],
    ]

    assert triangle(5, closed_repeat_row) == known_repeat
    assert triangle(5, closed_no_repeat_row) == known_no_repeat


def assert_brute_matches_closed(max_n: int, no_repeat: bool) -> None:
    """
    Compare brute force against closed form through max_n.
    """
    brute_row = brute_no_repeat_row if no_repeat else brute_repeat_row
    closed_row = closed_no_repeat_row if no_repeat else closed_repeat_row

    for n in range(max_n + 1):
        brute = brute_row(n)
        closed = closed_row(n)
        if brute != closed:
            raise AssertionError(
                f"mismatch at N={n}\n"
                f"brute:  {csv(brute)}\n"
                f"closed: {csv(closed)}"
            )


def self_test() -> None:
    """
    Run built-in reference checks.
    """
    assert_known_values()

    # Repeat-letter brute force grows as N^N, so keep this small.
    assert_brute_matches_closed(max_n=5, no_repeat=False)

    # No-repeat brute force is much smaller; this is still cheap.
    assert_brute_matches_closed(max_n=10, no_repeat=True)


# ---------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------

def selected_row_function(mode: str, no_repeat: bool) -> Callable[[int], Row]:
    if mode == "brute":
        return brute_no_repeat_row if no_repeat else brute_repeat_row
    if mode == "closed":
        return closed_no_repeat_row if no_repeat else closed_repeat_row
    raise ValueError(f"unknown mode: {mode}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compute the Harm.On.ica triangle."
    )
    parser.add_argument(
        "max_n",
        nargs="?",
        type=int,
        default=10,
        help="maximum N row to print; default: 10",
    )
    parser.add_argument(
        "--mode",
        choices=["brute", "closed"],
        default="closed",
        help="calculation method; default: closed",
    )
    parser.add_argument(
        "--no-repeat",
        action="store_true",
        help="use no-repeat mode, giving Pascal's triangle",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="run built-in tests before printing",
    )
    args = parser.parse_args()

    if args.max_n < 0:
        raise SystemExit("max_n must be nonnegative")

    if args.self_test:
        self_test()

    row_function = selected_row_function(args.mode, args.no_repeat)
    print_report(triangle(args.max_n, row_function))


if __name__ == "__main__":
    main()
