#!/usr/bin/env python3
"""Certify and export Artifact 18 quotient integer words.

The six text files are derived views of the complete retained Artifact 18
lanes.  The ordinary compact blocks cover post-seed event steps 1..50,000.
For d12, the complete experiment also has one documented centered-seed
PAIR_FACE event at exact time zero, step 0; that event is prepended to the
integer word.  The 24A and 24B lattice seeds declare no such time-zero pair
contact.

This tool does not trust ``pair_faces.u8`` alone: for every compact block it
verifies internal evidence checksums, exact chain linkage, the event-kind
stream, and the pairing of pair steps with face labels.  It separately checks
the retained initial-source record for each lane, then derives all native pair
labels in chronological collision order, reduces the first requested number of
labels, and either writes or verifies the saved words.

A successful ``--check`` establishes a data-derivation claim only.  It does
not establish that the compact evidence was generated by correct dynamics; an
independent exact replay remains a separate task.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import struct
import tarfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

LANES = ("d12", "24A", "24B")
VIEWS: dict[str, tuple[int, tuple[int, int]]] = {
    "d12": (12, (6, 3)),
    "24A": (24, (12, 6)),
    "24B": (24, (12, 6)),
}
REQUIRED_MEMBERS = {
    "BLOCK.json",
    "SHA256SUMS",
    "start_state.json",
    "end_state.json",
    "event_codes.u8",
    "pair_faces.u8",
    "pair_steps.u16",
    "complexity.csv.gz",
    "single_surface_audit.json",
    "receipt.json",
}


class CertificationError(RuntimeError):
    """Raised when the recorded corpus cannot support a word certificate."""


@dataclass(frozen=True)
class BlockEvidence:
    relative_path: str
    archive_sha256: str
    start_step: int
    end_step: int
    start_state: dict[str, Any]
    end_state: dict[str, Any]
    faces: bytes
    absolute_pair_steps: tuple[int, ...]


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical_state(state: dict[str, Any]) -> dict[str, Any]:
    try:
        return {key: state[key] for key in ("step", "exact_T", "state")}
    except KeyError as exc:
        raise CertificationError(f"missing exact state field {exc.args[0]!r}") from exc


def decode_archive(path: Path, lane: str, sides: int) -> BlockEvidence:
    """Read one compact block and validate the data needed for word derivation."""
    try:
        archive_digest = sha256_file(path)
        with tarfile.open(path, "r:gz") as archive:
            files = [member for member in archive.getmembers() if member.isfile()]
            roots = {PurePosixPath(member.name).parts[0] for member in files}
            if len(roots) != 1:
                raise CertificationError(f"{path.name}: archive must have one root")
            root = next(iter(roots))
            contents: dict[str, bytes] = {}
            for member in files:
                parts = PurePosixPath(member.name).parts
                if len(parts) != 2 or parts[0] != root:
                    raise CertificationError(f"{path.name}: unexpected member path {member.name!r}")
                base = parts[1]
                if base in contents:
                    raise CertificationError(f"{path.name}: duplicate member {base!r}")
                handle = archive.extractfile(member)
                if handle is None:
                    raise CertificationError(f"{path.name}: unreadable member {base!r}")
                contents[base] = handle.read()
    except (OSError, tarfile.TarError) as exc:
        raise CertificationError(f"{path}: cannot read compact archive: {exc}") from exc

    names = set(contents)
    if names != REQUIRED_MEMBERS:
        missing = sorted(REQUIRED_MEMBERS - names)
        extra = sorted(names - REQUIRED_MEMBERS)
        raise CertificationError(f"{path.name}: member mismatch; missing={missing}, extra={extra}")

    try:
        expected_checksums: dict[str, str] = {}
        for line in contents["SHA256SUMS"].decode("utf-8").splitlines():
            digest, name = line.split("  ", 1)
            if len(digest) != 64 or any(ch not in "0123456789abcdef" for ch in digest):
                raise CertificationError(f"{path.name}: malformed SHA-256 entry {line!r}")
            if name in expected_checksums:
                raise CertificationError(f"{path.name}: duplicate checksum member {name!r}")
            expected_checksums[name] = digest
    except UnicodeDecodeError as exc:
        raise CertificationError(f"{path.name}: SHA256SUMS is not UTF-8") from exc
    except ValueError as exc:
        raise CertificationError(f"{path.name}: malformed SHA256SUMS") from exc

    covered = names - {"SHA256SUMS"}
    if set(expected_checksums) != covered:
        raise CertificationError(f"{path.name}: checksum inventory does not match evidence inventory")
    for name, expected in expected_checksums.items():
        actual = sha256_bytes(contents[name])
        if actual != expected:
            raise CertificationError(f"{path.name}: checksum mismatch for {name}")

    try:
        block = json.loads(contents["BLOCK.json"])
        start_state = json.loads(contents["start_state.json"])
        end_state = json.loads(contents["end_state.json"])
        audit = json.loads(contents["single_surface_audit.json"])
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise CertificationError(f"{path.name}: malformed JSON evidence: {exc}") from exc

    if block.get("schema") != "exact-two-body-compact-block/v3":
        raise CertificationError(f"{path.name}: unsupported compact schema")
    if int(block.get("geometry", {}).get("polygon_sides", -1)) != sides:
        raise CertificationError(f"{path.name}: polygon-side mismatch for {lane}")
    if int(block.get("native_face_alphabet_size", -1)) != sides:
        raise CertificationError(f"{path.name}: native alphabet mismatch for {lane}")
    if not audit.get("accepted"):
        raise CertificationError(f"{path.name}: single-surface audit was not accepted")

    try:
        start_step = int(block["start"]["step"])
        end_step = int(block["end"]["step"])
        events = int(block["events"])
        if end_step - start_step != events:
            raise CertificationError(f"{path.name}: event-span mismatch")
        if int(start_state["step"]) != start_step or int(end_state["step"]) != end_step:
            raise CertificationError(f"{path.name}: endpoint step mismatch")
        if start_state.get("state_hash") != block["start"].get("state_hash"):
            raise CertificationError(f"{path.name}: start state-hash metadata mismatch")
        if end_state.get("state_hash") != block["end"].get("state_hash"):
            raise CertificationError(f"{path.name}: end state-hash metadata mismatch")
    except (KeyError, TypeError, ValueError) as exc:
        raise CertificationError(f"{path.name}: malformed endpoint metadata") from exc

    codes = contents["event_codes.u8"]
    faces = contents["pair_faces.u8"]
    raw_steps = contents["pair_steps.u16"]
    if len(codes) != events:
        raise CertificationError(f"{path.name}: event-code length {len(codes)} != {events}")
    if any(code not in (0, 1) for code in codes):
        raise CertificationError(f"{path.name}: event code outside WALL/PAIR alphabet")
    if len(raw_steps) % 2:
        raise CertificationError(f"{path.name}: odd pair_steps byte length")
    local_steps = struct.unpack("<" + "H" * (len(raw_steps) // 2), raw_steps)
    if len(local_steps) != len(faces):
        raise CertificationError(f"{path.name}: face/step cardinality mismatch")
    if int(block.get("pair_contact_count", -1)) != len(faces):
        raise CertificationError(f"{path.name}: pair-contact metadata mismatch")

    inferred_steps = tuple(index + 1 for index, code in enumerate(codes) if code == 1)
    if local_steps != inferred_steps:
        raise CertificationError(f"{path.name}: pair_steps does not exactly decode event_codes")
    if any(face >= sides for face in faces):
        raise CertificationError(f"{path.name}: face label outside 0..{sides - 1}")

    return BlockEvidence(
        relative_path=str(path),
        archive_sha256=archive_digest,
        start_step=start_step,
        end_step=end_step,
        start_state=start_state,
        end_state=end_state,
        faces=faces,
        absolute_pair_steps=tuple(start_step + step for step in local_steps),
    )


def load_initial_pair_event(root: Path, lane: str, sides: int) -> tuple[bytes, list[int], dict[str, Any]]:
    """Validate and return a declared time-zero seed pair event, if one exists.

    Compact blocks begin at step 0 *after* any centered-seed contact has been
    resolved.  The retained first-source record supplies that otherwise omitted
    event.  Lattice lanes certify an explicit absence of such a declaration.
    """
    source_dir = root / "supplementary" / "initial-block-source-records" / f"{lane}_000001_001000"
    manifest_path = source_dir / "manifest.json"
    if not manifest_path.is_file():
        raise CertificationError(f"{lane}: missing retained initial-source manifest {manifest_path}")
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        seed = manifest["seed"]
    except (OSError, KeyError, TypeError, json.JSONDecodeError) as exc:
        raise CertificationError(f"{lane}: malformed initial-source manifest") from exc
    if not isinstance(seed, dict):
        raise CertificationError(f"{lane}: seed declaration is not an object")

    source_record: dict[str, Any] = {
        "present": False,
        "source_manifest": str(manifest_path.relative_to(root)),
        "source_manifest_sha256": sha256_file(manifest_path),
    }
    declared = seed.get("time_zero_pair_face")
    if declared is None:
        source_record["declaration"] = "no time_zero_pair_face in retained seed manifest"
        return b"", [], source_record
    if isinstance(declared, bool) or not isinstance(declared, int) or not 0 <= declared < sides:
        raise CertificationError(f"{lane}: invalid time_zero_pair_face {declared!r}")

    faces_path = source_dir / "pair_faces.csv"
    if not faces_path.is_file():
        raise CertificationError(f"{lane}: missing retained initial pair-face record {faces_path}")
    try:
        with faces_path.open(newline="", encoding="utf-8") as handle:
            rows = csv.DictReader(handle)
            first = next(rows)
        row_index = int(first["pair_contact_index"])
        row_step = int(first["event_step"])
        row_face = int(first["face_label"])
    except (OSError, StopIteration, KeyError, TypeError, ValueError, csv.Error) as exc:
        raise CertificationError(f"{lane}: malformed retained initial pair-face record") from exc
    if (row_index, row_step, row_face) != (0, 0, declared):
        raise CertificationError(
            f"{lane}: initial record disagrees with seed declaration; "
            f"csv={(row_index, row_step, row_face)!r}, declared={declared!r}"
        )

    source_record.update({
        "present": True,
        "event_step": 0,
        "face_label": declared,
        "source_pair_faces_csv": str(faces_path.relative_to(root)),
        "source_pair_faces_csv_sha256": sha256_file(faces_path),
        "source_pair_contact_index": 0,
    })
    return bytes([declared]), [0], source_record


def certify_lane(root: Path, lane: str, target_events: int, terms: int) -> tuple[bytes, list[int], dict[str, Any]]:
    """Validate a lane and return its complete chronological native pair word."""
    sides, _ = VIEWS[lane]
    paths = sorted((root / "blocks" / lane).glob("*.block.tar.gz"))
    if not paths:
        raise CertificationError(f"{lane}: no compact blocks found")

    parsed: list[BlockEvidence] = [decode_archive(path, lane, sides) for path in paths]
    parsed.sort(key=lambda item: item.start_step)
    expected_start = 0
    previous_end: dict[str, Any] | None = None
    recorded_native = bytearray()
    recorded_pair_steps: list[int] = []
    inventory_lines: list[str] = []
    for block in parsed:
        if block.start_step != expected_start:
            raise CertificationError(
                f"{lane}: non-contiguous coverage before {Path(block.relative_path).name}; "
                f"expected start {expected_start}, got {block.start_step}"
            )
        if previous_end is not None and canonical_state(block.start_state) != canonical_state(previous_end):
            raise CertificationError(f"{lane}: exact end/start state chain mismatch before {Path(block.relative_path).name}")
        recorded_native.extend(block.faces)
        recorded_pair_steps.extend(block.absolute_pair_steps)
        inventory_lines.append(
            f"{Path(block.relative_path).relative_to(root)}\t{block.archive_sha256}\t"
            f"{block.start_step + 1}\t{block.end_step}\t{len(block.faces)}\n"
        )
        expected_start = block.end_step
        previous_end = block.end_state

    if expected_start != target_events:
        raise CertificationError(f"{lane}: coverage ends at {expected_start}, expected {target_events}")

    initial_native, initial_steps, initial_record = load_initial_pair_event(root, lane, sides)
    native = initial_native + bytes(recorded_native)
    pair_steps = initial_steps + recorded_pair_steps
    if len(native) < terms:
        raise CertificationError(f"{lane}: only {len(native)} native pair labels; need {terms}")
    if pair_steps != sorted(pair_steps) or len(set(pair_steps)) != len(pair_steps):
        raise CertificationError(f"{lane}: native pair-event steps are not strictly chronological")

    prefix = native[:terms]
    lane_record: dict[str, Any] = {
        "lane": lane,
        "polygon_sides": sides,
        "recorded_event_coverage": {"first": 1, "last": target_events, "count": target_events},
        "block_count": len(parsed),
        "internal_evidence_checksums": "verified for every compact block",
        "chain_linkage": "exact decoded end state equals next decoded start state",
        "event_pair_alignment": "pair_steps exactly equals the one-based PAIR positions in event_codes",
        "initial_pair_event": initial_record,
        "recorded_native_pair_label_count": len(recorded_native),
        "full_native_pair_label_count": len(native),
        "full_native_pair_label_sha256": sha256_bytes(native),
        "word_prefix_pair_label_count": terms,
        "word_prefix_first_global_event": pair_steps[0],
        "word_prefix_last_global_event": pair_steps[terms - 1],
        "word_prefix_native_label_sha256": sha256_bytes(prefix),
        "source_archive_inventory_sha256": sha256_bytes("".join(inventory_lines).encode("utf-8")),
    }
    return native, pair_steps, lane_record


def word_payload(residues: list[int]) -> bytes:
    return (",".join(str(value) for value in residues) + "\n").encode("utf-8")


def canonical_json(payload: Any) -> bytes:
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def build_certificates(root: Path, terms: int, target_events: int) -> tuple[dict[str, Any], dict[str, Any], dict[str, bytes]]:
    manifest: dict[str, Any] = {
        "artifact": 18,
        "format": "comma-separated decimal residues, one word per file",
        "terms_per_word": terms,
        "word_order": (
            "chronological pair contacts: any declared time-zero seed PAIR_FACE first, "
            "then pair contacts selected from recorded event steps 1..target_events"
        ),
        "views": [],
    }
    certificate: dict[str, Any] = {
        "schema": "artifact18-integer-word-certificate/v2",
        "artifact": 18,
        "scope": (
            "Data derivation only: every saved word is recomputed from the complete retained "
            "50,000-event compact lane, with a separately retained and cross-checked time-zero "
            "seed PAIR_FACE prepended whenever the seed declares one."
        ),
        "does_not_establish": (
            "That the retained compact corpus was generated by correct physics. "
            "That requires a fresh exact replay, preferably independent."
        ),
        "target_recorded_events_per_lane": target_events,
        "terms_per_word": terms,
        "lanes": [],
        "views": [],
    }
    outputs: dict[str, bytes] = {}

    for lane in LANES:
        native, _pair_steps, lane_record = certify_lane(root, lane, target_events, terms)
        certificate["lanes"].append(lane_record)
        sides, moduli = VIEWS[lane]
        prefix = native[:terms]
        for modulus in moduli:
            filename = f"{lane}_mod_{modulus}_first_{terms}.txt"
            payload = word_payload([label % modulus for label in prefix])
            digest = sha256_bytes(payload)
            view_record = {
                "lane": lane,
                "polygon_sides": sides,
                "modulus": modulus,
                "terms": terms,
                "file": filename,
                "sha256": digest,
                "source_recorded_event_coverage": {"first": 1, "last": target_events, "count": target_events},
                "initial_pair_event": lane_record["initial_pair_event"],
                "source_recorded_native_label_count": lane_record["recorded_native_pair_label_count"],
                "source_native_label_count": len(native),
                "prefix_first_global_event": lane_record["word_prefix_first_global_event"],
                "prefix_last_global_event": lane_record["word_prefix_last_global_event"],
                "full_native_pair_label_sha256": lane_record["full_native_pair_label_sha256"],
                "prefix_native_label_sha256": lane_record["word_prefix_native_label_sha256"],
                "source_archive_inventory_sha256": lane_record["source_archive_inventory_sha256"],
            }
            manifest["views"].append(view_record)
            certificate["views"].append({
                "file": filename,
                "lane": lane,
                "modulus": modulus,
                "sha256": digest,
                "terms": terms,
            })
            outputs[filename] = payload

    return manifest, certificate, outputs


def compare_or_write(path: Path, expected: bytes, check_only: bool) -> None:
    if check_only:
        if not path.exists():
            raise CertificationError(f"missing derived output {path}")
        actual = path.read_bytes()
        if actual != expected:
            raise CertificationError(f"derived output mismatch: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(expected)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--out-dir", type=Path, default=Path("words"))
    parser.add_argument("--terms", type=int, default=10_000)
    parser.add_argument("--target-events", type=int, default=50_000)
    parser.add_argument("--check", action="store_true", help="verify saved words/certificates; do not write")
    args = parser.parse_args()
    if args.terms < 1:
        raise SystemExit("--terms must be positive")
    if args.target_events < 1:
        raise SystemExit("--target-events must be positive")

    root = args.root.resolve()
    out = args.out_dir.resolve() if args.out_dir.is_absolute() else (root / args.out_dir).resolve()
    try:
        manifest, certificate, outputs = build_certificates(root, args.terms, args.target_events)
        for filename, payload in outputs.items():
            compare_or_write(out / filename, payload, args.check)
        compare_or_write(out / "WORDS_MANIFEST.json", canonical_json(manifest), args.check)
        compare_or_write(out / "WORDS_CERTIFICATE.json", canonical_json(certificate), args.check)
    except CertificationError as exc:
        raise SystemExit(f"FAIL words: {exc}") from exc

    mode = "verified" if args.check else "wrote"
    print(
        f"PASS Artifact 18 words: {mode} {len(outputs)} quotient words against "
        f"the complete {args.target_events}-event compact corpus in every lane"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
